# Generated by Django 4.2.7 on 2023-11-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='regd_date',
            field=models.DateTimeField(null=True),
        ),
    ]
