# Generated by Django 4.2.7 on 2023-11-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_regd_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=8)),
                ('size', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
